### ISSUE TITLE
Korora 21 Beta Pharlap startup error

### ISSUE THREAD

**Issue by aldorgan** [kororaproject/kp#60]
Hi!
I got this error message when i'm trying to start up pharlap from gnome-terminal:

Traceback (most recent call last):
  File "/bin/pharlap", line 130, in <module>
    system = System().to_dict()
  File "/usr/lib/python3.4/site-packages/lens/system.py", line 42, in __init__
    self._build_cpu_info()
  File "/usr/lib/python3.4/site-packages/lens/system.py", line 83, in _build_cpu_info
    self._cpu['clockMax'] = int(float(m.group(1)) * 1e6)
ValueError: could not convert string to float: '1000,0000'

**Comment by DarkEra** [comment]
Closing this one because the issue has been reopened here: https://github.com/kororaproject/kp-pharlap/issues/14
